FROM ruby:3.3.4-slim

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential curl git libpq-dev libvips pkg-config && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

WORKDIR /rails

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE 3005

CMD ["bash", "-lc", "bin/rails db:prepare db:seed && bin/rails server -b 0.0.0.0 -p 3005"]
